init:
  - git config --global core.autocrlf input

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\MinGW\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install sass
  - gem install minitest
  - git submodule update --recursive --init
  - SET SASS_LIBSASS_PATH=libsass

test_script:
  - msbuild sassc-win.sln /t:Build /p:Configuration=Release;Platform=Win32
  - c:\mingw\msys\1.0\bin\sh c:/projects/sassc-win/sassc-win/libsass/script/cibuild

build: off
