init:
  - git config --global core.autocrlf input

platform:
  - Win32
  - Win64

configuration:
  - Debug
  - Release

build:
  project: sassc-win.sln 
  verbosity: detailed

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install sass
  - git submodule update --recursive --init
  - SET SASS_LIBSASS_PATH=libsass

test_script:
  - bin\sassc -h
