init:
  - git config --global core.autocrlf input

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\MinGW\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install sass
  - git submodule update --recursive --init
  - SET SASS_LIBSASS_PATH=libsass

test_script:
  - msbuild sassc-win.sln /t:Build /p:Configuration=Release;Platform=Win32
  - bin\sassc -h

build: off
