init:
  - git config --global core.autocrlf input

platform:
  - Win32
  - Win64

configuration:
  - Release

build:
  project: sassc-win.sln 
  verbosity: detailed

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install sass minitest
  - git submodule update --recursive --init

test_script:
  - bin\sassc -h
  - ruby sassc-win/sass-spec/sass-spec.rb -c bin/sassc sassc-win/sass-spec/spec
